---
title: "2. Model Evaluation and Plot"
output: html_document
date: "2026-01-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages
```{r}
library(StMoMo)
library(demography)
library(stats)
```

Define country labels
```{r}
# Define labels
labels <- names(stmomo_datasets)
```

Specify Model Equations
```{r}
# Model equations
M7 <- m7(link = "logit")
M6 <- m6(link = "logit")
M5 <- cbd(link = "logit")
```

Inverse Logit Function
```{r}
# Inverse logit function
inv_logit <- function(x) {
  1/(1 + exp(-x))
}
```

### Specify R1, R2, and B Population
```{r}
# Specify model populations
model_populations <- c("UK", "ENW", "sim_ENW")

# Specify dataset into fit 
R1_data <- stmomo_datasets[[model_populations[1]]]
R2_data <- stmomo_datasets[[model_populations[2]]]
B_data  <- stmomo_datasets[[model_populations[3]]]

# R1, R2 and B qxt
R1_qxt <- R1_data$Dxt / R1_data$Ext
R2_qxt <- R2_data$Dxt / R2_data$Ext
B_qxt  <- B_data$Dxt / B_data$Ext
```

BIC table
```{r, warning = FALSE}
# Create model list
model_list <- list(
  M7 = M7,
  M6 = M6,
  M5 = M5
)

# Create matrix to store BIC
models_BIC <- matrix(NA, nrow = 27, ncol = 7)
colnames(models_BIC) <- c("R1 Model", "R2 Model", "B Model", "R1 BIC", "R2 BIC", "B BIC", "Joint BIC")

# Loop for all model specifications
row <- 1

for (i in 1:length(model_list)) {
  # Specify R1 model
  R1 <- names(model_list[i])
  R1_model <- model_list[[i]]

  for (j in 1:length(model_list)) {
    # Specify R2 model
    R2 <- names(model_list[j])
    R2_model <- model_list[[j]]
    
    for (k in 1:length(model_list)) {
      # Specify B_model
      B_3 <- names(model_list[k])
      B_3_model <- model_list[[k]]
      
      # R1 Fit
      hide_output_dummy <- capture.output(R1_fit <- fit(R1_model, data = R1_data))
      R1_fitted <- fitted(R1_fit)
      # R2 Fit
      hide_output_dummy <- capture.output(R2_fit <- fit(R2_model, data = R2_data, oxt = R1_fitted))
      R2_fitted <- fitted(R2_fit)
      # B_3 Fit
      hide_output_dummy <- capture.output(B_3_fit <- fit(B_3_model, data = B_data, oxt = R2_fitted))
      B_3_fitted <- fitted(B_3_fit)
      
      # Store results
      models_BIC[row, "R1 Model"] <- R1
      models_BIC[row, "R2 Model"] <- R2
      models_BIC[row, "B Model"]<- B_3
      models_BIC[row, "R1 BIC"] <- round(BIC(R1_fit), 2)
      models_BIC[row, "R2 BIC"] <- round(BIC(R2_fit), 2)
      models_BIC[row, "B BIC"]<- round(BIC(B_3_fit), 2)
      models_BIC[row, "Joint BIC"] <- round(sum(BIC(R1_fit), BIC(R2_fit), BIC(B_3_fit)), 2)
      
      # Move on to next row
      row <- row + 1
    }
  }
}

print(model_populations)
print(models_BIC)
```

# Select model specifications
```{r}
R1_model  <- M7
R2_model  <- M5
B_3_model <- M5
```

R1 Model
```{r, warning = FALSE}
if (identical(R1_model, M7)) {
  # M7 Fit
  hide_output_dummy <- capture.output(
    R1_fit <- fit(R1_model, data = R1_data)
  )

  # Storing R1 fitted value
  R1_fitted <- fitted(R1_fit)

  # Cohort effect
  par(mfrow = c(1, 2))
  plot(seq(min(year_range - age_upper), max(year_range - age_lower)), R1_fit$gc, 
       type = "l", xlab = "t-x", ylab = "gamma", main = paste0("R1: ", R1_data$label))
  plot(seq(min(year_range - age_upper) + 1, max(year_range - age_lower)), diff(R1_fit$gc), 
       type = "l", xlab = "t-x", ylab = "1st differenced gamma", main = paste0("R1: ", R1_data$label))

  # age effects with time
  par(mfrow = c(1, 3))
  plot(year_range, R1_fit$kt[1, ], type = "l", 
       xlab = "Calendar Year (t)", ylab = "kappa 1", main = paste0("R1: ", R1_data$label)) # level
  plot(year_range, R1_fit$kt[2, ], type = "l", 
       xlab = "Calendar Year (t)", ylab = "kappa 2", main = paste0("R1: ", R1_data$label)) # slope
  plot(year_range, R1_fit$kt[3, ], type = "l", 
       xlab = "Calendar Year (t)", ylab = "kappa 3", main = paste0("R1: ", R1_data$label)) # curvature

  # residuals plot
  plot(residuals(R1_fit), main = paste0("R1: ", R1_data$label))
  
} else if (identical(R1_model, M6)) {
  # M6 fit
  hide_output_dummy <- capture.output(
    R1_fit <- fit(R1_model, data = R1_data)
  )

  # Storing R1 fitted value
  R1_fitted <- fitted(R1_fit)

  # Cohort effect
  par(mfrow = c(1, 2))
  plot(seq(min(year_range - age_upper), max(year_range - age_lower)), R1_fit$gc, 
       type = "l", xlab = "t-x", ylab = "gamma", main = paste0("R1: ", R1_data$label))
  plot(seq(min(year_range - age_upper) + 1, max(year_range - age_lower)), diff(R1_fit$gc), 
       type = "l", xlab = "t-x", ylab = "1st differenced gamma", main = paste0("R1: ", R1_data$label))

  # age effects with time
  par(mfrow = c(1, 3))
  plot(year_range, R1_fit$kt[1, ], type = "l", 
       xlab = "Calendar Year (t)", ylab = "kappa 1", main = paste0("R1: ", R1_data$label)) # level
  plot(year_range, R1_fit$kt[2, ], type = "l", 
       xlab = "Calendar Year (t)", ylab = "kappa 2", main = paste0("R1: ", R1_data$label)) # slope

  # residuals plot
  plot(residuals(R1_fit), main = paste0("R1: ", R1_data$label))
} else if (identical(R1_model, M5)) {
  # M5 fit
  hide_output_dummy <- capture.output(
    R1_fit <- fit(R1_model, data = R1_data)
  )

  # Storing R1 fitted value
  R1_fitted <- fitted(R1_fit)

  # age effects with time
  par(mfrow = c(1, 3))
  plot(year_range, R1_fit$kt[1, ], type = "l", 
       xlab = "Calendar Year (t)", ylab = "kappa 1", main = paste0("R1: ", R1_data$label)) # level
  plot(year_range, R1_fit$kt[2, ], type = "l", 
       xlab = "Calendar Year (t)", ylab = "kappa 2", main = paste0("R1: ", R1_data$label)) # slope

  # residuals plot
  plot(residuals(R1_fit), main = paste0("R1: ", R1_data$label))
} else {
  print("R1 Model specification not included/correct")
}
```

R2 Model
```{r, warning = FALSE}
if (identical(R2_model, M7)) {
  # M7 Fit
  hide_output_dummy <- capture.output(
    R2_fit <- fit(R2_model, data = R2_data, oxt = R1_fitted) # oxt is the offset)
  )

  # Storing R2 fitted value
  R2_fitted <- fitted(R2_fit)

  # Cohort effect
  par(mfrow = c(1, 2))
  plot(seq(min(year_range - age_upper), max(year_range - age_lower)), R2_fit$gc, 
       type = "l", xlab = "t-x", ylab = "gamma", main = paste0("R2: ", R2_data$label))
  plot(seq(min(year_range - age_upper) + 1, max(year_range - age_lower)), diff(R2_fit$gc), 
       type = "l", xlab = "t-x", ylab = "1st differenced gamma", main = paste0("R2: ", R2_data$label))

  # age effects with time
  par(mfrow = c(1, 3))
  plot(year_range, R2_fit$kt[1, ], type = "l", 
       xlab = "Calendar Year (t)", ylab = "kappa 1", main = paste0("R2: ", R2_data$label)) # level
  plot(year_range, R2_fit$kt[2, ], type = "l", 
       xlab = "Calendar Year (t)", ylab = "kappa 2", main = paste0("R2: ", R2_data$label)) # slope
  plot(year_range, R2_fit$kt[3, ], type = "l", 
       xlab = "Calendar Year (t)", ylab = "kappa 3", main = paste0("R2: ", R2_data$label)) # curvature

  # residuals plot
  plot(residuals(R2_fit), main = paste0("R2: ", R2_data$label))
  
} else if (identical(R2_model, M6)) {
  # M6 fit
  hide_output_dummy <- capture.output(
    R2_fit <- fit(R2_model, data = R2_data, oxt = R1_fitted) # oxt is the offset
  )

  # Storing R2 fitted value
  R2_fitted <- fitted(R2_fit)

  # Cohort effect
  par(mfrow = c(1, 2))
  plot(seq(min(year_range - age_upper), max(year_range - age_lower)), R2_fit$gc, 
       type = "l", xlab = "t-x", ylab = "gamma", main = paste0("R2: ", R2_data$label))
  plot(seq(min(year_range - age_upper) + 1, max(year_range - age_lower)), diff(R2_fit$gc), 
       type = "l", xlab = "t-x", ylab = "1st differenced gamma", main = paste0("R2: ", R2_data$label))

  # age effects with time
  par(mfrow = c(1, 3))
  plot(year_range, R2_fit$kt[1, ], type = "l", 
       xlab = "Calendar Year (t)", ylab = "kappa 1", main = paste0("R2: ", R2_data$label)) # level
  plot(year_range, R2_fit$kt[2, ], type = "l", 
       xlab = "Calendar Year (t)", ylab = "kappa 2", main = paste0("R2: ", R2_data$label)) # slope

  # residuals plot
  plot(residuals(R2_fit), main = paste0("R2: ", R2_data$label))
} else if (identical(R2_model, M5)) {
  # M5 fit
  hide_output_dummy <- capture.output(
    R2_fit <- fit(R2_model, data = R2_data, oxt = R1_fitted) # oxt is the offset
  )

  # Storing R2 fitted value
  R2_fitted <- fitted(R2_fit)

  # age effects with time
  par(mfrow = c(1, 3))
  plot(year_range, R2_fit$kt[1, ], type = "l", 
       xlab = "Calendar Year (t)", ylab = "kappa 1", main = paste0("R2: ", R2_data$label)) # level
  plot(year_range, R2_fit$kt[2, ], type = "l", 
       xlab = "Calendar Year (t)", ylab = "kappa 2", main = paste0("R2: ", R2_data$label)) # slope

  # residuals plot
  plot(residuals(R2_fit), main = paste0("R2: ", R2_data$label))
} else {
  print("R2 Model specification not included/correct")
}
```

B_3 Model
```{r, warning = FALSE}
if (identical(B_3_model, M7)) {
  # M7 Fit
  hide_output_dummy <- capture.output(
    B_3_fit <- fit(B_3_model, data = B_data, oxt = R2_fitted) # oxt is the offset)
  )

  # Storing B_3 fitted value
  b_3_fitted <- fitted(B_3_fit)

  # Cohort effect
  par(mfrow = c(1, 2))
  plot(seq(min(year_range - age_upper), max(year_range - age_lower)), B_3_fit$gc, 
       type = "l", xlab = "t-x", ylab = "gamma", main = paste0("B: ", B_data$label))
  plot(seq(min(year_range - age_upper) + 1, max(year_range - age_lower)), diff(B_3_fit$gc), 
       type = "l", xlab = "t-x", ylab = "1st differenced gamma", main = paste0("B: ", B_data$label))


  # age effects with time
  par(mfrow = c(1, 3))
  plot(year_range, B_3_fit$kt[1, ], type = "l", 
       xlab = "Calendar Year (t)", ylab = "kappa 1", main = paste0("B: ", B_data$label)) # level
  plot(year_range, B_3_fit$kt[2, ], type = "l", 
       xlab = "Calendar Year (t)", ylab = "kappa 2", main = paste0("B: ", B_data$label)) # slope
  plot(year_range, B_3_fit$kt[3, ], type = "l", 
       xlab = "Calendar Year (t)", ylab = "kappa 3", main = paste0("B: ", B_data$label)) # curvature


  # residuals plot
  plot(residuals(B_3_fit), main = paste0("B_3: ", B_data$label))
  
} else if (identical(B_3_model, M6)) {
  # M6 fit
  hide_output_dummy <- capture.output(
    B_3_fit <- fit(B_3_model, data = B_data, oxt = R2_fitted) # oxt is the offset
  )

  # Storing B_3 fitted value
  B_3_fitted <- fitted(B_3_fit)

  # Cohort effect
  par(mfrow = c(1, 2))
  plot(seq(min(year_range - age_upper), max(year_range - age_lower)), B_3_fit$gc, 
       type = "l", xlab = "t-x", ylab = "gamma", main = paste0("B: ", B_data$label))
  plot(seq(min(year_range - age_upper) + 1, max(year_range - age_lower)), diff(B_3_fit$gc), 
       type = "l", xlab = "t-x", ylab = "1st differenced gamma", main = paste0("B: ", B_data$label))

  # age effects with time
  par(mfrow = c(1, 3))
  plot(year_range, B_3_fit$kt[1, ], type = "l", 
       xlab = "Calendar Year (t)", ylab = "kappa 1", main = paste0("B: ", B_data$label)) # level
  plot(year_range, B_3_fit$kt[2, ], type = "l", 
       xlab = "Calendar Year (t)", ylab = "kappa 2", main = paste0("B: ", B_data$label)) # slope

  # residuals plot
  plot(residuals(B_3_fit), main = paste0("B_3: ", B_data$label))
} else if (identical(B_3_model, M5)) {
  # M5 fit
  hide_output_dummy <- capture.output(
    B_3_fit <- fit(B_3_model, data = B_data, oxt = R2_fitted) # oxt is the offset
  )

  # Storing B_3 fitted value
  B_3_fitted <- fitted(B_3_fit)

  # age effects with time
  par(mfrow = c(1, 3))
  plot(year_range, B_3_fit$kt[1, ], type = "l", 
       xlab = "Calendar Year (t)", ylab = "kappa 1", main = paste0("B: ", B_data$label)) # level
  plot(year_range, B_3_fit$kt[2, ], type = "l", 
       xlab = "Calendar Year (t)", ylab = "kappa 2", main = paste0("B: ", B_data$label)) # slope

  # residuals plot
  plot(residuals(B_3_fit), main = paste0("B: ", B_data$label))
} else {
  print("B_3 Model specification not included/correct")
}
```

Plotting Three Population CBD (M7-M6-M5) Model R1, R2, and B fit
```{r}
# Open a larger window (width & height in inches)
dev.new(width = 12, height = 10)

par(mfrow = c(2, 2),
    mar = c(4, 4, 3, 1))  # margins: bottom, left, top, right

# Plotting R1 fit
plot_ages <- c("60", "70", "80", "90")
calendar_year <- as.numeric(colnames(R1_qxt))

# par(mfrow = c(2, 2))
for (i in 1:length(plot_ages)) {
  age <- plot_ages[i]
  # Plot raw mortality rate vs fitted
  plot(calendar_year, R1_qxt[age, ], 
       main = paste("R1: ", R1_data$label, " Population Mortality \n vs Fitted (Age ", age, ")", sep = ""),
       xlab = "Calendar Year (t)", ylab = paste(R1_data$label, " q", age, ",t", sep = ""))
  lines(calendar_year, inv_logit(R1_fitted[age, ]), type = "l")
}
```
```{r}
# Open a larger window (width & height in inches)
dev.new(width = 12, height = 10)

par(mfrow = c(2, 2),
    mar = c(4, 4, 3, 1))  # margins: bottom, left, top, right

# Plotting R2 fit
plot_ages <- c("60", "70", "80", "90")
calendar_year <- as.numeric(colnames(R2_qxt))

#par(mfrow = c(2, 2))
for (i in 1:length(plot_ages)) {
  age <- plot_ages[i]
  # Plot raw mortality rate vs fitted
  plot(calendar_year, R2_qxt[age, ], 
       main = paste("R2: ", R2_data$label, " Population Mortality \n vs Fitted (Age ", age, ")", sep = ""),
       xlab = "Calendar Year (t)", ylab = paste(R2_data$label, " q", age, ",t", sep = ""))
  lines(calendar_year, inv_logit(R2_fitted[age, ]), type = "l")
}
```
```{r}
# Open a larger window (width & height in inches)
dev.new(width = 12, height = 10)

par(mfrow = c(2, 2),
    mar = c(4, 4, 3, 1))  # margins: bottom, left, top, right

# Plotting B_3 fit
plot_ages <- c("60", "70", "80", "90")
calendar_year <- as.numeric(colnames(B_qxt))

# par(mfrow = c(1, 1))
for (i in 1:length(plot_ages)) {
  age <- plot_ages[i]
  # Plot raw mortality rate vs fitted
  plot(calendar_year, B_qxt[age, ], 
       main = paste("B: ", B_data$label, " Population Mortality \n vs Fitted (Age ", age, ")", sep = ""),
       xlab = "Calendar Year (t)", ylab = paste(B_data$label, " q", age, ",t", sep = ""))
  lines(calendar_year, inv_logit(B_3_fitted[age, ]), type = "l")
}
```

BIC Values
```{r}
CBD_BIC <- matrix(nrow = 3, ncol = 1)
rownames(CBD_BIC) <- c("R1", "R2", "B")
colnames(CBD_BIC) <- c("BIC")

CBD_BIC["R1", "BIC"] <- BIC(R1_fit)
CBD_BIC["R2", "BIC"] <- BIC(R2_fit)
CBD_BIC["B", "BIC"] <- BIC(B_3_fit)

print(CBD_BIC)
```


















