---
title: "Time Series Forecasting"
output: pdf_document
date: "2025-09-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages
```{r}
library(StMoMo)
library(demography)
library(stats)
library(forecast)
library(vars)
library(MASS)
```

Set forecast and simulation duration
```{r}
h <- 50

year_range <- year_range
year_forecast <- (max(year_range) + 1):(max(year_range) + h)
cohort_range <- R1_fit$cohorts
cohort_forecast <- (max(cohort_range) + 1):(max(cohort_range) + h)
```


```{r}
test <- forecast(R1_fit, h = 50, gc.order = c(1, 1, 0))
plot(test, only.kt = TRUE, nCol = 3) 
plot(test, only.gc = TRUE)
```

###  Three Population CBD (M7-M6-M5) Forecast

Store parameters
```{r}
# R1 Population
if (identical(R1_model, M7)) {
  # M7
  kt1_R1 <- R1_fit$kt[1, ]
  kt2_R1 <- R1_fit$kt[2, ]
  kt3_R1 <- R1_fit$kt[3, ]
  kt_R1 <- rbind(kt1_R1, kt2_R1, kt3_R1)

  gc_R1 <- R1_fit$gc
  
} else if (identical(R1_model, M6)) {
  # M6
  kt1_R1 <- R1_fit$kt[1, ]
  kt2_R1 <- R1_fit$kt[2, ]
  kt_R1 <- rbind(kt1_R1, kt2_R1)

  gc_R1 <- R1_fit$gc
  
} else if (identical(R1_model, M5)) {
  # M5
  kt1_R1 <- R1_fit$kt[1, ]
  kt2_R1 <- R1_fit$kt[2, ]
  kt_R1 <- rbind(kt1_R1, kt2_R1)
  
} else {
  print("R1 Model specification not included/correct")
}

# R2 Population
if (identical(R2_model, M7)) {
  # M7
  kt1_R2 <- R2_fit$kt[1, ]
  kt2_R2 <- R2_fit$kt[2, ]
  kt3_R2 <- R2_fit$kt[3, ]
  kt_R2 <- cbind(kt1_R2, kt2_R2, kt3_R2)

  gc_R2 <- R2_fit$gc
  
} else if (identical(R2_model, M6)) {
  # M6
  kt1_R2 <- R2_fit$kt[1, ]
  kt2_R2 <- R2_fit$kt[2, ]
  kt_R2 <- cbind(kt1_R2, kt2_R2)

  gc_R2 <- R2_fit$gc
  
} else if (identical(R2_model, M5)) {
  # M5
  kt1_R2 <- R2_fit$kt[1, ]
  kt2_R2 <- R2_fit$kt[2, ]
  kt_R2 <- cbind(kt1_R2, kt2_R2)
  
} else {
  print("R2 Model specification not included/correct")
}

# B_3 Population
if (identical(B_3_model, M7)) {
  # M7
  kt1_B_3 <- B_3_fit$kt[1, ]
  kt2_B_3 <- B_3_fit$kt[2, ]
  kt3_B_3 <- B_3_fit$kt[3, ]
  kt_B_3 <- cbind(kt1_B_3, kt2_B_3, kt3_B_3)

  gc_B_3 <- B_3_fit$gc
  
} else if (identical(B_3_model, M6)) {
  # M6
  kt1_B_3 <- B_3_fit$kt[1, ]
  kt2_B_3 <- B_3_fit$kt[2, ]
  kt_B_3 <- cbind(kt1_B_3, kt2_B_3)

  gc_B_3 <- B_3_fit$gc
  
} else if (identical(B_3_model, M5)) {
  # M5
  kt1_B_3 <- B_3_fit$kt[1, ]
  kt2_B_3 <- B_3_fit$kt[2, ]
  kt_B_3 <- cbind(kt1_B_3, kt2_B_3)
  
} else {
  print("R2 Model specification not included/correct")
}
```

Time Series Modelling on Stored Parameters
```{r}
# R1 Modelling

# MRWD fit on kt_R1
kt_R1_fit <- mrwd(kt_R1)
kt_R1_drift <- kt_R1_fit$drift
kt_R1_sigma <- kt_R1_fit$sigma
kT_R1 <- kt_R1[, ncol(kt_R1)] # last observed kappas

# ARIMA(1,1,0) on gc_R1 for M6 or M7 model
if (identical(R1_model, M7) || identical(R1_model, M6)){
  gc_R1_fit <- Arima(gc_R1, order = c(1, 1, 0), include.constant = TRUE)
}

################################################################################

# R2 Modelling

# VAR(1) fit on kt_R2
kt_R2_fit <- VAR(kt_R2, p = 1)

# AR(1) on gc_R2 for M6 or M7 model
if (identical(R2_model, M7) || identical(R2_model, M6)){
  gc_R2_fit <- Arima(gc_R2, order = c(1, 0, 0), include.constant = TRUE)
}

################################################################################

# B3 Modelling

# VAR(1) fit on kt_B_3
kt_B_3_fit <- VAR(kt_B_3, p = 1)

# AR(1) on gc_B_3 for M6 or M7 model
if (identical(B_3_model, M7) || identical(B_3_model, M6)){
  gc_B_3_fit <- Arima(gc_B_3, order = c(1, 0, 0), include.constant = TRUE)
}
```

Forecast Time Series on Stored Parameters
```{r}
# R1 Forecast

# MRWD forecast on kt_R1
mean_kt_R1_f <- matrix(nrow = nrow(kt_R1), ncol = h,
                       dimnames = list(paste0("kt", 1:nrow(kt_R1)),
                                       year_forecast))
cov_kt_R1_f <- vector("list", h)
lower95_kt_R1_f <- upper95_kt_R1_f <- mean_kt_R1_f

for (i in 1:h) {
  # Mean and Covariance
  mean_kt_R1_f[, i] <- i*kt_R1_drift + kT_R1
  cov_kt_R1_f[[i]] <- i*kt_R1_sigma
  
  # Lower and Upper 95%
  se_i <- sqrt(diag(cov_kt_R1_f[[i]]))  # std dev for each kt at horizon i
  lower95_kt_R1_f[, i] <- mean_kt_R1_f[, i] - 1.96 * se_i
  upper95_kt_R1_f[, i] <- mean_kt_R1_f[, i] + 1.96 * se_i
}

# ARIMA(1,1,0) forecast on gc_R1 for M6 or M7 model
if (identical(R1_model, M7) || identical(R1_model, M6)) {
  mean_gc_R1_f <- matrix(nrow = 1, ncol = h,
                         dimnames = list(paste0("gc"), cohort_forecast))
  lower95_gc_R1_f <- upper95_gc_R1_f <- mean_gc_R1_f

  gc_R1_f <- forecast(gc_R1_fit, h = h)
  for (i in 1:h) {
    mean_gc_R1_f[i] <- gc_R1_f$mean[i]
    lower95_gc_R1_f[i] <- gc_R1_f$lower[i, "95%"]
    upper95_gc_R1_f[i] <- gc_R1_f$upper[i, "95%"]
  }
}

################################################################################

# R2 Forecast

# VAR(1) forecast on kt_R2
mean_kt_R2_f <- matrix(nrow = ncol(kt_R2), ncol = h,
                       dimnames = list(paste0("kt", 1:ncol(kt_R2)),
                                       year_forecast))
lower95_kt_R2_f <- upper95_kt_R2_f <- mean_kt_R2_f

kt_R2_f <- predict(kt_R2_fit, n.ahead = h, ci = 0.95)
for (i in 1:h) {
  # kt1_R2
  mean_kt_R2_f["kt1", i] <- kt_R2_f$fcst$kt1_R2[i, "fcst"]
  lower95_kt_R2_f["kt1", i] <- kt_R2_f$fcst$kt1_R2[i, "lower"]
  upper95_kt_R2_f["kt1", i] <- kt_R2_f$fcst$kt1_R2[i, "upper"]
  
  # kt2_R2
  mean_kt_R2_f["kt2", i] <- kt_R2_f$fcst$kt2_R2[i, "fcst"]
  lower95_kt_R2_f["kt2", i] <- kt_R2_f$fcst$kt2_R2[i, "lower"]
  upper95_kt_R2_f["kt2", i] <- kt_R2_f$fcst$kt2_R2[i, "upper"]
  
  # kt3_R2 for M7 model
  if (identical(R2_model, M7)) {
  mean_kt_R2_f["kt3", i] <- kt_R2_f$fcst$kt3_R2[i, "fcst"]
  lower95_kt_R2_f["kt3", i] <- kt_R2_f$fcst$kt3_R2[i, "lower"]
  upper95_kt_R2_f["kt3", i] <- kt_R2_f$fcst$kt3_R2[i, "upper"]
  }
}

# AR(1) forecast on gc_R2 for M6 or M7 model
if (identical(R2_model, M7) || identical(R2_model, M6)) {
  mean_gc_R2_f <- matrix(nrow = 1, ncol = h,
                         dimnames = list(paste0("gc"), cohort_forecast))
  lower95_gc_R2_f <- upper95_gc_R2_f <- mean_gc_R2_f

  gc_R2_f <- forecast(gc_R2_fit, h = h)
  for (i in 1:h) {
    mean_gc_R2_f[i] <- gc_R2_f$mean[i]
    lower95_gc_R2_f[i] <- gc_R2_f$lower[i, "95%"]
    upper95_gc_R2_f[i] <- gc_R2_f$upper[i, "95%"]
  }
}

################################################################################

# B_3 Forecast

# VAR(1) forecast on kt_B_3
mean_kt_B_3_f <- matrix(nrow = ncol(kt_B_3), ncol = h,
                       dimnames = list(paste0("kt", 1:ncol(kt_B_3)),
                                       year_forecast))
lower95_kt_B_3_f <- upper95_kt_B_3_f <- mean_kt_B_3_f

kt_B_3_f <- predict(kt_B_3_fit, n.ahead = h, ci = 0.95)
for (i in 1:h) {
  # kt1_B_3
  mean_kt_B_3_f["kt1", i] <- kt_B_3_f$fcst$kt1_B_3[i, "fcst"]
  lower95_kt_B_3_f["kt1", i] <- kt_B_3_f$fcst$kt1_B_3[i, "lower"]
  upper95_kt_B_3_f["kt1", i] <- kt_B_3_f$fcst$kt1_B_3[i, "upper"]
  
  # kt2_B_3
  mean_kt_B_3_f["kt2", i] <- kt_B_3_f$fcst$kt2_B_3[i, "fcst"]
  lower95_kt_B_3_f["kt2", i] <- kt_B_3_f$fcst$kt2_B_3[i, "lower"]
  upper95_kt_B_3_f["kt2", i] <- kt_B_3_f$fcst$kt2_B_3[i, "upper"]
    
  # kt3_R2 for M7 model
  if (identical(B_3_model, M7)) {
    mean_kt_B_3_f["kt3", i] <- kt_B_3_f$fcst$kt3_B_3[i, "fcst"]
    lower95_kt_B_3_f["kt3", i] <- kt_B_3_f$fcst$kt3_B_3[i, "lower"]
    upper95_kt_B_3_f["kt3", i] <- kt_B_3_f$fcst$kt3_B_3[i, "upper"]
  }
}

# AR(1) forecast on gc_B_3 for M6 or M7 model
if (identical(B_3_model, M7) || identical(B_3_model, M6)) {
  mean_gc_B_3_f <- matrix(nrow = 1, ncol = h,
                         dimnames = list(paste0("gc"), cohort_forecast))
  lower95_gc_B_3_f <- upper95_gc_B_3_f <- mean_gc_B_3_f

  gc_B_3_f <- forecast(gc_B_3_fit, h = h)
  for (i in 1:h) {
    mean_gc_B_3_f[i] <- gc_B_3_f$mean[i]
    lower95_gc_B_3_f[i] <- gc_B_3_f$lower[i, "95%"]
    upper95_gc_B_3_f[i] <- gc_B_3_f$upper[i, "95%"]
  }
}
```

Plot Time Series on Stored Parameters
```{r}
dev.new(width = 14, height = 10)

# R1 Forecast Plots

# MRWD forecast on kt_R1 plot
n_plots_R1_kt <- nrow(kt_R1)
par(mfrow = c(ceiling(n_plots_R1_kt / 2), 2),
    mar = c(4, 4, 3, 1))

for (i in 1:nrow(kt_R1)) {
  # Observed kt
  plot(year_range, kt_R1[i, ], type = "l", lwd = 1, col = "black",
       xlim = c(min(year_range), max(year_forecast)),
       ylim = range(c(kt_R1[i, ], lower95_kt_R1_f[i, ], upper95_kt_R1_f[i, ])),
       xlab = "Year", ylab = paste("R1", rownames(mean_kt_R1_f)[i]),
       main = paste("R1:", R1_data$label, "Forecast for", rownames(mean_kt_R1_f)[i]))
  
  # Kt forecast mean
  lines(year_forecast, mean_kt_R1_f[i, ], col = "red", lwd = 1)
  
  # Connect last observed (2019) to first forecast (2020)
  lines(c(max(year_range), min(year_forecast)),
        c(kt_R1[i, ncol(kt_R1)], mean_kt_R1_f[i, 1]),
        col = "red", lty = 1)
  
  # prediction intervals
  lines(year_forecast, lower95_kt_R1_f[i, ], col = "blue", lty = 1)
  lines(year_forecast, upper95_kt_R1_f[i, ], col = "blue", lty = 1)
  
  # optional shading
  polygon(c(year_forecast, rev(year_forecast)),
          c(lower95_kt_R1_f[i, ], rev(upper95_kt_R1_f[i, ])),
          col = rgb(0, 0, 1, 0.2), border = NA)
}

# ARIMA(1,1,0) forecast on gc_R1 plot for M6 and M7
if (identical(R1_model, M7) || identical(R1_model, M6)) {
  
  plot(cohort_range, gc_R1, type = "l", lwd = 1, col = "black",
     xlim = c(min(cohort_range), max(cohort_forecast)),
     ylim = range(c(gc_R1, lower95_gc_R1_f, upper95_gc_R1_f)),
     xlab = "Cohort", ylab = paste("R1", rownames(mean_gc_R1_f)),
     main = paste("R1:", R1_data$label, "Forecast for", rownames(mean_gc_R1_f)))

  # gc_R1 forecast mean
  lines(cohort_forecast, mean_gc_R1_f, col = "red", lwd = 1)

  # Connect last observed (1959) to first forecast (1960)
  lines(c(max(cohort_range), min(cohort_forecast)),
        c(gc_R1[length(gc_R1)], mean_gc_R1_f[1]), # use length instead of ncol for row = 1
        col = "red", lty = 1)  

  # prediction intervals
  lines(cohort_forecast, lower95_gc_R1_f, col = "blue", lty = 1)
  lines(cohort_forecast, upper95_gc_R1_f, col = "blue", lty = 1)

  # optional shading
  polygon(c(cohort_forecast, rev(cohort_forecast)),
          c(lower95_gc_R1_f, rev(upper95_gc_R1_f)),
          col = rgb(0, 0, 1, 0.2), border = NA)
}

################################################################################

# R2 forecast plots

# VAR(1) forecast on kt_R1 plots
n_plots_R2_kt <- nrow(kt_R2)
par(mfrow = c(2, 2),
    mar = c(4, 4, 3, 1))

for (i in 1:ncol(kt_R2)) {
  # Observed kt
  plot(year_range, kt_R2[, i], type = "l", lwd = 1, col = "black",
       xlim = c(min(year_range), max(year_forecast)),
       ylim = range(c(kt_R2[, i], lower95_kt_R2_f[i, ], upper95_kt_R2_f[i, ])),
       xlab = "Year", ylab = paste("R2", rownames(mean_kt_R2_f)[i]),
       main = paste("R2:", R2_data$label, "Forecast for", rownames(mean_kt_R2_f)[i]))
  
  # Kt forecast mean
  lines(year_forecast, mean_kt_R2_f[i, ], col = "red", lwd = 1)
  
  # Connect last observed (2019) to first forecast (2020)
  lines(c(max(year_range), min(year_forecast)),
        c(kt_R2[nrow(kt_R2), i], mean_kt_R2_f[i, 1]),
        col = "red", lty = 1)
  
  # prediction intervals
  lines(year_forecast, lower95_kt_R2_f[i, ], col = "blue", lty = 1)
  lines(year_forecast, upper95_kt_R2_f[i, ], col = "blue", lty = 1)
  
  # optional shading
  polygon(c(year_forecast, rev(year_forecast)),
          c(lower95_kt_R2_f[i, ], rev(upper95_kt_R2_f[i, ])),
          col = rgb(0, 0, 1, 0.2), border = NA)
}

# ARIMA(1,0,0) forecast on gc_R2 plot for M6 and M7
if (identical(R2_model, M7) || identical(R2_model, M6)) {
  # AR(1) forecast on gc_R2 plot
  plot(cohort_range, gc_R2, type = "l", lwd = 1, col = "black",
      xlim = c(min(cohort_range), max(cohort_forecast)),
      ylim = range(c(gc_R2, lower95_gc_R2_f, upper95_gc_R2_f)),
      xlab = "Cohort", ylab = paste("R2", rownames(mean_gc_R2_f)),
      main = paste("R2:", R2_data$label, "Forecast for", rownames(mean_gc_R2_f)))
  
  lines(cohort_forecast, mean_gc_R2_f, col = "red", lwd = 1)

  # Connect last observed (1959) to first forecast (1960)
  lines(c(max(cohort_range), min(cohort_forecast)),
        c(gc_R2[length(gc_R2)], mean_gc_R2_f[1]), # use length instead of ncol for row = 1
        col = "red", lty = 1)  

  # prediction intervals
  lines(cohort_forecast, lower95_gc_R2_f, col = "blue", lty = 1)
  lines(cohort_forecast, upper95_gc_R2_f, col = "blue", lty = 1)

  # optional shading
  polygon(c(cohort_forecast, rev(cohort_forecast)),
          c(lower95_gc_R2_f, rev(upper95_gc_R2_f)),
          col = rgb(0, 0, 1, 0.2), border = NA)
}

################################################################################

# B_3 forecast plots

# VAR(1) forecast on kt_B_3 plots
n_plots_B_3_kt <- nrow(kt_B_3)
par(mfrow = c(2, 2),
    mar = c(4, 4, 3, 1))

for (i in 1:ncol(kt_B_3)) {
  # Observed kt
  plot(year_range, kt_B_3[, i], type = "l", lwd = 1, col = "black",
       xlim = c(min(year_range), max(year_forecast)),
       ylim = range(c(kt_B_3[, i], lower95_kt_B_3_f[i, ], upper95_kt_B_3_f[i, ])),
       xlab = "Year", ylab = paste("B", rownames(mean_kt_B_3_f)[i]),
       main = paste("B:", B_data$label, "Forecast for", rownames(mean_kt_B_3_f)[i]))
  
  # Kt forecast mean
  lines(year_forecast, mean_kt_B_3_f[i, ], col = "red", lwd = 1)
  
  # Connect last observed (2019) to first forecast (2020)
  lines(c(max(year_range), min(year_forecast)),
        c(kt_B_3[nrow(kt_B_3), i], mean_kt_B_3_f[i, 1]),
        col = "red", lty = 1)
  
  # prediction intervals
  lines(year_forecast, lower95_kt_B_3_f[i, ], col = "blue", lty = 1)
  lines(year_forecast, upper95_kt_B_3_f[i, ], col = "blue", lty = 1)
  
  # optional shading
  polygon(c(year_forecast, rev(year_forecast)),
          c(lower95_kt_B_3_f[i, ], rev(upper95_kt_B_3_f[i, ])),
          col = rgb(0, 0, 1, 0.2), border = NA)
}

# ARIMA(1,0,0) forecast on gc_B_3 plot for M6 and M7
if (identical(B_3_model, M7) || identical(B_3_model, M6)) {
  # AR(1) forecast on gc_B_3 plot
  plot(cohort_range, gc_B_3, type = "l", lwd = 1, col = "black",
      xlim = c(min(cohort_range), max(cohort_forecast)),
      ylim = range(c(gc_B_3, lower95_gc_B_3_f, upper95_gc_B_3_f)),
      xlab = "Cohort", ylab = paste("B", rownames(mean_gc_B_3_f)),
      main = paste("B:", B_data$label, "Forecast for", rownames(mean_gc_B_3_f)))
  
  lines(cohort_forecast, mean_gc_B_3_f, col = "red", lwd = 1)

  # Connect last observed (1959) to first forecast (1960)
  lines(c(max(cohort_range), min(cohort_forecast)),
        c(gc_B_3[length(gc_B_3)], mean_gc_B_3_f[1]), # use length instead of ncol for row = 1
        col = "red", lty = 1)  

  # prediction intervals
  lines(cohort_forecast, lower95_gc_B_3_f, col = "blue", lty = 1)
  lines(cohort_forecast, upper95_gc_B_3_f, col = "blue", lty = 1)

  # optional shading
  polygon(c(cohort_forecast, rev(cohort_forecast)),
          c(lower95_gc_B_3_f, rev(upper95_gc_B_3_f)),
          col = rgb(0, 0, 1, 0.2), border = NA)
}
```

Assess roots
```{r}
if (identical(R1_model, M7) || identical(R1_model, M6)) {
  cat("gc_R1 Roots ARIMA(1,1,0):\n")
  print(gc_R1_fit$coef["ar1"])
  cat("\n")
}

if (identical(R2_model, M7) || identical(R2_model, M6)) {
  cat("gc_R2 Roots AR(1):\n")
  print(gc_R2_fit$coef["ar1"])
  cat("\n")
}

if (identical(B_3_model, M7) || identical(B_3_model, M6)) {
  cat("gc_B_3 Roots AR(1):\n")
  print(gc_B_3_fit$coef["ar1"])
  cat("\n")
}

cat("kt_R2 Roots VAR(1):\n")
roots(kt_R2_fit)
cat("\n")

cat("kt_B_3 Roots VAR(1):\n")
roots(kt_B_3_fit)
```

